"use client";
import { useEffect, useMemo, useState } from "react";
import { BookOpen, CheckCircle2, Clock3, TrendingUp, Wallet } from "lucide-react";
import { Button } from "@codi-1/ui/components/button";
import { Card, CardContent, CardHeader, CardTitle } from "@codi-1/ui/components/card";
type ProfileData = { activities: { occurredAt: string; type: string }[]; enrollments: { enrollment: { progress: number }; course: { id: string; title: string } }[]; transactions: { id: string; createdAt: string; courseId: string; amount: number; currency: string; status: string }[] };
export default function StudentProfileOverview() {
 const [tab,setTab]=useState("overview"); const [year,setYear]=useState(new Date().getFullYear()); const [data,setData]=useState<ProfileData|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null);
 useEffect(()=>{const c=new AbortController();setLoading(true);setError(null);fetch(`/api/student/profile?year=${year}`,{signal:c.signal}).then(async r=>{const body=await r.json().catch(()=>null);if(!r.ok)throw new Error(typeof body?.error==="string"?body.error:"Không thể tải dữ liệu hồ sơ.");return body as ProfileData}).then(setData).catch(e=>{if(e instanceof Error&&e.name!=="AbortError")setError(e.message)}).finally(()=>{if(!c.signal.aborted)setLoading(false)});return()=>c.abort()},[year]);
 const activities=data?.activities??[]; const activeDays=useMemo(()=>new Set(activities.map(a=>{const d=new Date(a.occurredAt);return `${d.getFullYear()}-${d.getMonth()}-${d.getDate()}`})).size,[activities]);
 const activity=useMemo(()=>{const v=Array(371).fill(0) as number[],start=new Date(year,0,1),counts=new Map<string,number>();activities.forEach(a=>{const d=new Date(a.occurredAt),k=`${d.getFullYear()}-${d.getMonth()}-${d.getDate()}`;counts.set(k,(counts.get(k)??0)+1)});counts.forEach((n,k)=>{const [y,m,d]=k.split("-").map(Number),i=Math.floor((new Date(y,m,d).getTime()-start.getTime())/86400000);if(y===year&&i>=0&&i<v.length)v[i]=Math.min(4,n)});return v},[activities,year]);
 const courses=(data?.enrollments??[]).map(({enrollment,course})=>({...course,progress:enrollment.progress,status:enrollment.progress>=100?"Đã hoàn thành":"Đang học"}));
 return <div className="space-y-5"><nav className="flex gap-1 border-b border-border" aria-label="Điều hướng hồ sơ">{[["overview","Tổng quan"],["courses","Khóa học"],["transactions","Giao dịch"]].map(([id,label])=><button key={id} type="button" onClick={()=>setTab(id)} className={`border-b-2 px-3 py-2 text-xs ${tab===id?"border-primary text-primary":"border-transparent text-muted-foreground"}`}>{label}</button>)}</nav>{loading&&<p role="status" className="text-sm text-muted-foreground">Đang tải dữ liệu hồ sơ…</p>}{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}{!loading&&!error&&data&&<>
 {(tab==="overview"||tab==="courses")&&<Card><CardHeader><CardTitle className="flex items-center gap-2"><BookOpen className="size-4 text-primary"/>Khóa học của tôi</CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2">{courses.length===0?<p className="text-sm text-muted-foreground">Bạn chưa đăng ký khóa học nào.</p>:courses.map(c=><div key={c.id} className="border border-border p-4"><div className="flex justify-between"><h3 className="text-sm font-medium">{c.title}</h3><span className="text-xs text-muted-foreground">{c.status}</span></div><div className="my-3 h-1.5 bg-muted"><div className="h-full bg-primary" style={{width:`${c.progress}%`}}/></div><div className="flex justify-between text-xs text-muted-foreground"><span>{c.progress}% hoàn thành</span><Button variant="link" size="xs" className="h-auto p-0" disabled>{c.progress===100?"Xem lại":"Tiếp tục học"}</Button></div></div>)}</CardContent></Card>}
 {tab==="overview"&&<Card><CardHeader><CardTitle className="flex justify-between text-base"><span>{activeDays} ngày hoạt động trong năm {year}</span></CardTitle></CardHeader><CardContent><div className="grid grid-flow-col grid-rows-7 gap-1 overflow-x-auto" aria-label={`Heatmap thời gian hoạt động năm ${year}`}>{activity.map((n,i)=><span key={i} title={`${n} hoạt động`} className={`size-3 rounded-[3px] ${["bg-muted","bg-[#9be9a8]","bg-[#40c463]","bg-[#30a14e]","bg-[#216e39]"][n]}`}/>)}</div><p className="mt-3 text-xs text-muted-foreground">{activeDays?"Hoạt động học tập theo ngày":"Chưa có hoạt động học tập"}</p><label className="mt-2 flex justify-end text-xs">Năm<select aria-label="Chọn năm" value={year} onChange={e=>setYear(Number(e.target.value))} className="ml-2 border border-border bg-background px-2 py-1 text-foreground [&>option]:bg-background [&>option]:text-foreground">{[year,year-1,year-2].map(y=><option className="bg-background text-foreground" key={y} value={y}>{y}</option>)}</select></label></CardContent></Card>}
 {tab==="transactions"&&<Card><CardHeader><CardTitle className="flex items-center gap-2"><Wallet className="size-4 text-primary"/>Lịch sử giao dịch</CardTitle></CardHeader><CardContent>{data.transactions.length===0?<p className="text-sm text-muted-foreground">Chưa có giao dịch nào.</p>:data.transactions.map(t=><div key={t.id} className="flex gap-3 border-b py-3 text-xs"><span>{t.id}</span><span>{new Date(t.createdAt).toLocaleDateString("vi-VN")}</span><span>{t.amount.toLocaleString("vi-VN")} {t.currency}</span><span className="text-primary"><CheckCircle2 className="inline size-3.5"/> {t.status}</span></div>)}</CardContent></Card>}
 </>}</div>;
}
export function ProfileStats(){const [stats,setStats]=useState({progress:"Chưa có dữ liệu",activeDays:"Chưa có dữ liệu"});useEffect(()=>{fetch(`/api/student/profile?year=${new Date().getFullYear()}`).then(r=>{if(!r.ok)throw new Error();return r.json()}).then((v:ProfileData)=>{const p=v.enrollments.length?`${Math.round(v.enrollments.reduce((s,r)=>s+r.enrollment.progress,0)/v.enrollments.length)}%`:"Chưa có dữ liệu";const d=new Set(v.activities.map(a=>new Date(a.occurredAt).toLocaleDateString("en-CA"))).size;setStats({progress:p,activeDays:d?`${d} ngày`:"Chưa có dữ liệu"})}).catch(()=>undefined)},[]);return <div className="grid gap-3 sm:grid-cols-2"><Stat icon={<TrendingUp/>} label="Tiến độ trung bình" value={stats.progress}/><Stat icon={<Clock3/>} label="Ngày hoạt động" value={stats.activeDays}/></div>}
function Stat({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <Card><CardContent className="flex items-center gap-3 p-4"><span className="text-primary">{icon}</span><div><p className="text-xs text-muted-foreground">{label}</p><p className="font-semibold">{value}</p></div></CardContent></Card>}
