name: Auto Add Issues to Project

on:
  issues:
    types:
      - opened
      - reopened

jobs:
  add-to-project:
    name: Add Issue to Project
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to Codi Product Board
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/users/blu1606/projects/1
          github-token: ${{ secrets.GH_PROJECT_TOKEN || secrets.GITHUB_TOKEN }}
